# Generated by Django 6.0.4 on 2026-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_moment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
